// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmGjbBCM9zi5rE_hGiaxAEIoUwjig8kQA',
    appId: '1:13455900632:web:259592b3ccb897f4557cad',
    messagingSenderId: '13455900632',
    projectId: 'reservapp-a2ad7',
    authDomain: 'reservapp-a2ad7.firebaseapp.com',
    storageBucket: 'reservapp-a2ad7.appspot.com',
    measurementId: 'G-1XJ6E84J4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdyNFcY__qvl2INjtFD2sYK2OEizu18Lc',
    appId: '1:13455900632:android:ccf9983e9932dc99557cad',
    messagingSenderId: '13455900632',
    projectId: 'reservapp-a2ad7',
    storageBucket: 'reservapp-a2ad7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpQemvHKR6RwYoXKQiZ-IfjIXR1UdntmY',
    appId: '1:13455900632:ios:c9a4f633070f688a557cad',
    messagingSenderId: '13455900632',
    projectId: 'reservapp-a2ad7',
    storageBucket: 'reservapp-a2ad7.appspot.com',
    iosClientId: '13455900632-ofmji9rd5nt912l2b82h6n0npc8bu471.apps.googleusercontent.com',
    iosBundleId: 'com.example.reservasTheo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpQemvHKR6RwYoXKQiZ-IfjIXR1UdntmY',
    appId: '1:13455900632:ios:c9a4f633070f688a557cad',
    messagingSenderId: '13455900632',
    projectId: 'reservapp-a2ad7',
    storageBucket: 'reservapp-a2ad7.appspot.com',
    iosClientId: '13455900632-ofmji9rd5nt912l2b82h6n0npc8bu471.apps.googleusercontent.com',
    iosBundleId: 'com.example.reservasTheo',
  );
}
